.TH RHYME 1
.SH NAME
rhyme \- a data-centric expressive query language
.SH SYNOPSIS
.B rhyme
[\fIfile\fR | \fIquery\fR]
.IR args *
.SH DESCRIPTION
.B rhyme
Runs a Rhyme query either from a .rh file, or given inline as first argument.

Available inputs are 'stdin' for JSON data piped into stdin, and 'argv' for
command line arguments.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message

.SH SEE ALSO
Website: \fBhttps://rhyme-lang.github.io\fR

GitHub: \fBhttps://github.com/rhyme-lang/rhyme\fR
