# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Install Nlohmann Json
      run: |
        git clone https://github.com/nlohmann/json.git
        sudo cp -r json/include/* /usr/include/
    - name: Generate TPCH data files
      run: |
        git clone https://github.com/electrum/tpch-dbgen.git
        make -C tpch-dbgen
        tpch-dbgen/dbgen -s 1 -f -b ./tpch-dbgen/dists.dss
        chmod 664 *.tbl
        mkdir -v -p cgen-sql/data/SF1
        mv -v *.tbl cgen-sql/data/SF1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
